/**
 * Scoring Engine (Section 22)
 * Transparent, deterministic analytical calculation.
 * Overall score is NOT simply generated by the LLM.
 *
 * Formula:
 * Market Demand: 20%
 * Customer Pain: 15%
 * Competition: 10%
 * Differentiation: 15%
 * Monetization: 15%
 * Market Timing: 10%
 * Distribution Difficulty: 5% (inverted: higher score = less difficult / more favorable)
 * Execution Difficulty: 5% (inverted: higher score = less difficult / more favorable)
 * Risk: 5% (inverted: higher score = lower risk / more favorable)
 */

import { ScoringBreakdown } from '../../src/types';

export interface RawScoreInputs {
  marketDemand: number; // 0 - 100
  customerPain: number; // 0 - 100
  competition: number; // 0 - 100 (favorable market dynamics = higher score)
  differentiation: number; // 0 - 100
  monetization: number; // 0 - 100
  timing: number; // 0 - 100
  distributionDifficulty: number; // 0 - 100 (100 = easy/organic distribution, 0 = high friction)
  executionDifficulty: number; // 0 - 100 (100 = straightforward execution, 0 = severe complexity)
  risk: number; // 0 - 100 (100 = manageable/low risk, 0 = catastrophic risk)
}

export function clamp(val: number, min = 0, max = 100): number {
  return Math.min(Math.max(val, min), max);
}

export function calculateDeterministicScore(inputs: RawScoreInputs): ScoringBreakdown {
  const md = clamp(inputs.marketDemand);
  const cp = clamp(inputs.customerPain);
  const comp = clamp(inputs.competition);
  const diff = clamp(inputs.differentiation);
  const mon = clamp(inputs.monetization);
  const tim = clamp(inputs.timing);
  const dist = clamp(inputs.distributionDifficulty);
  const exec = clamp(inputs.executionDifficulty);
  const rsk = clamp(inputs.risk);

  const overall =
    md * 0.20 +
    cp * 0.15 +
    comp * 0.10 +
    diff * 0.15 +
    mon * 0.15 +
    tim * 0.10 +
    dist * 0.05 +
    exec * 0.05 +
    rsk * 0.05;

  return {
    overall: Math.round(overall * 10) / 10,
    marketDemand: Math.round(md),
    customerPain: Math.round(cp),
    competition: Math.round(comp),
    differentiation: Math.round(diff),
    monetization: Math.round(mon),
    timing: Math.round(tim),
    distributionDifficulty: Math.round(dist),
    executionDifficulty: Math.round(exec),
    risk: Math.round(rsk),
    methodology:
      'Deterministic Weighted Average: (MarketDemand*0.20) + (CustomerPain*0.15) + (Competition*0.10) + (Differentiation*0.15) + (Monetization*0.15) + (Timing*0.10) + (Distribution*0.05) + (Execution*0.05) + (Risk*0.05). Scores are normalized to a 0-100 scale.',
  };
}
